// lib/domain/entities/playlist.dart
// Aura — Playlist entity (freezed, immutable).
// PRD §6.2: supports both user-created and Smart Mix playlists.

import 'package:freezed_annotation/freezed_annotation.dart';

part 'playlist.freezed.dart';
part 'playlist.g.dart';

/// Identifies what kind of playlist this is.
enum PlaylistType {
  /// Standard user-created playlist.
  userCreated,

  /// Generated by SmartMixGenerator (daily mixes, mood mixes).
  smartMix,

  /// Auto-populated: "Recently Played", "Most Played", etc.
  autoGenerated,
}

/// Mood category used for Smart Mixes (PRD §6.4).
enum MixMood { morning, workout, chill, focus, evening }

@freezed
class Playlist with _$Playlist {
  const factory Playlist({
    /// Unique identifier (UUID v4).
    required String id,

    /// Display name.
    required String name,

    /// Optional description / subtitle.
    @Default('') String description,

    /// Type of playlist — controls display and behaviour.
    @Default(PlaylistType.userCreated) PlaylistType type,

    /// If this is a smart mix, which mood it represents.
    MixMood? mood,

    /// Ordered list of track IDs (order matters for non-shuffle playback).
    @Default([]) List<String> trackIds,

    /// Epoch ms when created.
    required int createdAtMs,

    /// Epoch ms of last modification.
    required int updatedAtMs,

    /// Optional cover art path (overrides default album-art mosaic in UI).
    String? coverArtPath,

    /// Whether this playlist is pinned to the top of the library.
    @Default(false) bool isPinned,
  }) = _Playlist;

  factory Playlist.fromJson(Map<String, dynamic> json) =>
      _$PlaylistFromJson(json);
}
