// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'playlist.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$PlaylistImpl _$$PlaylistImplFromJson(Map<String, dynamic> json) =>
    _$PlaylistImpl(
      id: json['id'] as String,
      name: json['name'] as String,
      description: json['description'] as String? ?? '',
      type:
          $enumDecodeNullable(_$PlaylistTypeEnumMap, json['type']) ??
          PlaylistType.userCreated,
      mood: $enumDecodeNullable(_$MixMoodEnumMap, json['mood']),
      trackIds:
          (json['trackIds'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          const [],
      createdAtMs: (json['createdAtMs'] as num).toInt(),
      updatedAtMs: (json['updatedAtMs'] as num).toInt(),
      coverArtPath: json['coverArtPath'] as String?,
      coverArtPaths:
          (json['coverArtPaths'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          const [],
      isPinned: json['isPinned'] as bool? ?? false,
    );

Map<String, dynamic> _$$PlaylistImplToJson(_$PlaylistImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'type': _$PlaylistTypeEnumMap[instance.type]!,
      'mood': _$MixMoodEnumMap[instance.mood],
      'trackIds': instance.trackIds,
      'createdAtMs': instance.createdAtMs,
      'updatedAtMs': instance.updatedAtMs,
      'coverArtPath': instance.coverArtPath,
      'coverArtPaths': instance.coverArtPaths,
      'isPinned': instance.isPinned,
    };

const _$PlaylistTypeEnumMap = {
  PlaylistType.userCreated: 'userCreated',
  PlaylistType.smartMix: 'smartMix',
  PlaylistType.autoGenerated: 'autoGenerated',
};

const _$MixMoodEnumMap = {
  MixMood.morning: 'morning',
  MixMood.workout: 'workout',
  MixMood.chill: 'chill',
  MixMood.focus: 'focus',
  MixMood.evening: 'evening',
};
